# Generated by Django 3.1.7 on 2021-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDirectories', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='key',
            field=models.BinaryField(default=b'0000000000000000', max_length=16),
            preserve_default=False,
        ),
    ]
