# Generated by Django 3.1.7 on 2021-03-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainDirectories', '0003_datafile_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
    ]
