# Generated by Django 3.1.7 on 2021-03-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainDirectories', '0004_remove_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='privatekeygen',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publickeygen',
            field=models.BinaryField(default=b''),
            preserve_default=False,
        ),
    ]
