# Generated by Django 3.1.7 on 2021-03-17 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainDirectories', '0005_auto_20210317_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_received', to=settings.AUTH_USER_MODEL)),
                ('data_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_sent', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainDirectories.datafile')),
            ],
        ),
    ]
